language: python
python:
    - 3.6
before_install:
    - sudo rm -f /etc/boto.cfg
install:
    - pip install coverage

addons:
    sonarcloud:
        organization: "usdot-jpo-sdc"
script: 
    - coverage erase
    - sonar-scanner -X -D sonar.login=$SONAR_TOKEN
